package com.AdvertisementMicroservice.AdvertisementMicroservice.Entitys;


public enum NotificationType {
	TAKE_ADVERTISEMENT,
	REJECTED_TAKE_ADVERTISEMENT,
	ACCEPTED_TAKE_ADVERTISEMENT,
	RECEIVE_SERVICE,
	REJECTED_RECEIVE_SERVICE,
	ACCEPTED_RECEIVE_SERVICE,
	
}
